### ISSUE TITLE
zsh-autocomplete fails to load with zcomet

### ISSUE THREAD

**Issue by jack1142** [agkozak/zcomet#3] opened 2021-10-05 08:59 UTC
I get this error message on startup:
```
(anon):22: bad pattern: funcs=(\n      ~zsh-autocomplete/functions/.autocomplete.*~*.zwc(N-.:a)\n  )
Cannot source /home/ubuntu/.zcomet/repos/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh.
ubuntu-virtual-machine% 
```
Contents of `.zshrc`:
```
# Clone zcomet if necessary
if [[ ! -f ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh ]]; then
  command git clone https://github.com/agkozak/zcomet.git ${ZDOTDIR:-${HOME}}/.zcomet/bin
fi

source ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh

zcomet load marlonrichert/zsh-autocomplete
```

See the response from zsh-autocomplete's author claiming that this is in fact a bug in zcomet:
https://github.com/marlonrichert/zsh-autocomplete/issues/335#issuecomment-934106907

**Comment by marlonrichert** [comment] 2021-10-05 11:11
I don't just claim it, I can actually demonstrate it in a reproducible way:
```zsh
% cd $(mktemp -d)
git clone --depth 1 -- https://github.com/agkozak/zcomet.git $PWD/.zcomet/bin
> .zshrc <<EOF
PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
source $PWD/.zcomet/bin/zcomet.zsh
zcomet load marlonrichert/zsh-autocomplete
EOF
env -i HOME=$PWD ZDOTDIR=$PWD FPATH=$FPATH TERM=$TERM zsh -d

/tmp/tmp.EZGp1Vxc1f/
Cloning into '/tmp/tmp.EZGp1Vxc1f/.zcomet/bin'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 25 (delta 2), reused 13 (delta 2), pack-reused 0
Receiving objects: 100% (25/25), 511.18 KiB | 412.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
Cloning marlonrichert/zsh-autocomplete:
Cloning into '/tmp/tmp.EZGp1Vxc1f/.zcomet/repos/marlonrichert/zsh-autocomplete'...
remote: Enumerating objects: 3247, done.
remote: Counting objects: 100% (950/950), done.
remote: Compressing objects: 100% (488/488), done.
remote: Total 3247 (delta 654), reused 729 (delta 451), pack-reused 2297
Receiving objects: 100% (3247/3247), 4.18 MiB | 1.33 MiB/s, done.
Resolving deltas: 100% (2289/2289), done.
(anon):22: bad pattern: funcs=(\n      ~zsh-autocomplete/functions/.autocomplete.*~*.zwc(N-.:a)\n  )
Cannot source /tmp/tmp.EZGp1Vxc1f/.zcomet/repos/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh.
% zcompile -R .zcomet/repos/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% exec zsh -d
%
```
Now `zsh-autocomplete` works just fine.

**Comment by marlonrichert** [comment] 2021-10-05 11:13
> See the response from zsh-autocomplete's author claiming that this is in fact a bug in zcomet:
marlonrichert/zsh-autocomplete#335 (comment)

Or rather, please read [my comment on the same bug in Z Init](https://github.com/zdharma/zinit/issues/543#issuecomment-920677219).

**Comment by agkozak** [comment] 2021-10-05 16:54
@jack1142 Thanks for your patience. I'm sure I'll have this fixed soon.

@marlonrichert You're right to point to the compiled wordcode as the source of the problem, and your demonstration works for me. But even changing my original `zcompile -UzR` to `zcompile -R` in `zcomet.zsh` doesn't fix the problem; running `zcompile -R` on the command line does. It will be interesting to figure out what's happening differently inside the `zcomet.zsh` script.

**Comment by marlonrichert** [comment] 2021-10-05 17:46
> But even changing my original `zcompile -UzR` to `zcompile -R` in `zcomet.zsh` doesn't fix the problem

Sorry, I missed that you were already using the `-R` flag to compile scripts. I just assumed you were doing the exact same thing as Z Init, as your plugin manager produced the exact same error. My bad.

**Comment by marlonrichert** [comment] 2021-10-05 17:53
> running `zcompile -R` on the command line does. It will be interesting to figure out what's happening differently inside the `zcomet.zsh` script.

It's not that complicated, really. Here, I submitted a fix for you: #4

**Comment by marlonrichert** [comment] 2021-10-05 18:39
On further investigation, it turns out that, actually, the only thing that fixes the problem, for both Z Init and Z Comet, is to `zcompile` from the command line. Changing the `zcompile` statement inside the code does nothing to solve it. 😕

**Comment by agkozak** [comment] 2021-10-06 06:54
As far as I can tell, simply running `zcompile` in an anonymous function on the command line

    () { zcompile -R zsh-autocomplete.plugin.zsh; }

will also produce the error

    (anon):22: bad pattern: funcs=(\n      ~zsh-autocomplete/functions/.autocomplete.*~*.zwc(N-.:a)\n  )

No plugin manager involved.

**Comment by agkozak** [comment] 2021-10-06 18:11
@jack1142 Did that help?

**Closed** 2021-10-06 18:46 UTC
